version: '3'
services:
  mojopaste:
    # image: "jhthorsen/mojopaste"
    image: mojopaste_dev
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/data
      - ./:/app-mojopaste-master
    environment:
      MOJO_MODE: development
      PASTE_BACKEND: Mongo
    command: ["/usr/bin/perl", "/app-mojopaste-master/script/mojopaste", "prefork", "-l", "http://*:8080"]
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
