version: '3'
services:
  mojopaste:
    image: "jhthorsen/mojopaste"
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/data
      - ./script:/app-mojopaste-master/script
      - ./lib:/app-mojopaste-master/lib
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
