version: '3'
services:
  mojopaste:
    image: "jhthorsen/mojopaste"
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/data
      - ./:/app-mojopaste-master
    environment:
      MOJO_MODE: development
      PASTE_BACKEND: Mongo
  mongo:
    image: mongo
    restart: always
