version: '3'
services:
  mojopaste:
    image: mojopate_mongo
    build: .
    ports:
      - "5555:8080"
    volumes:
      - ./lib:/app-mojopaste-master/lib
    environment:
      PASTE_BACKEND: Mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./dbdata:/data/db
